package ru.mejiomah17.tinkoff.api.model.grouped.requests.accounts

import kotlinx.serialization.Serializable
import ru.mejiomah17.tinkoff.api.model.common.Amount
import ru.mejiomah17.tinkoff.api.model.common.Currency

@Serializable
data class AccountPayload(
    val accountBalance: Amount? = null,
    val accountGroup: String? = null,
    val accountIconType: String? = null,
    val accountType: String? = null,
    val afterNextStatementDate: AfterNextStatementDate? = null,
    val authorizationsAmount: Amount? = null,
    val c2cOutLimit: Amount? = null,
    val c2cOutLimitBorder: Amount? = null,
    val cardNumbers: List<CardNumber> = emptyList(),
    val clientUnverifiedFlag: String? = null,
    val creationDate: CreationDate? = null,
    val creditLimit: Amount? = null,
    val currency: Currency? = null,
    val currentMinimalPayment: Amount? = null,
    val currentRecommendedPayment: Amount? = null,
    val debtAmount: Amount? = null,
    val debtAmountWithAuths: Amount? = null,
    val debtBalance: Amount? = null,
    val defaultMonthlyCashLimit: Amount? = null,
    val defaultMonthlyTinkoffCashInsertionLimit: Amount? = null,
    val defaultMonthlyTinkoffCashLimit: Amount? = null,
    val defaultRenewalAmountLeft: Amount? = null,
    val dueDate: DueDate? = null,
    val emoneyFlag: Boolean? = null,
    val externalAccountNumber: String? = null,
    val feeAndFinesBalance: Amount? = null,
    val feeNextChargeDate: FeeNextChargeDate? = null,
    val feeNextChargeText: String? = null,
    val hidden: Boolean? = null,
    val id: String? = null,
    val identificationState: String? = null,
    val imported: Boolean? = null,
    val interest: Amount? = null,
    val isCrowdfunding: Boolean? = null,
    val lastPaymentDate: LastPaymentDate? = null,
    val lastStatementDate: LastStatementDate? = null,
    val lastStatementDebtAmount: Amount? = null,
    val linkedAccountNumber: String? = null,
    val loyalty: List<Loyalty>,
    val marketingName: String? = null,
    val moneyAmount: Amount? = null,
    val monthlyCashLimit: Amount? = null,
    val monthlyTinkoffCashInsertionLimit: Amount? = null,
    val monthlyTinkoffCashLimit: Amount? = null,
    val multiCardCluster: MultiCardCluster? = null,
    val name: String? = null,
    val nextStatementDate: NextStatementDate? = null,
    val overdraftFee: Amount? = null,
    val overdraftStatus: String? = null,
    val partNumber: String? = null,
    val pastDueDebt: Amount? = null,
    val rate: Double? = null,
    val rateHint: RateHint? = null,
    val renewalAmountLeft: Amount? = null,
    val restructuringAccount: Boolean? = null,
    val status: String? = null,
    val sumPurchases: Double? = null,
    val tariffFileHash: String? = null,
    val tariffInfo: TariffInfo? = null,
    val totalExpense: Amount? = null,
    val totalIncome: Amount
)