package ru.mejiomah17.tinkoff.api.model.grouped.requests.accounts

import kotlinx.serialization.Serializable

@Serializable
data class AccountPayload(
    val accountBalance: AccountBalance? = null,
    val accountGroup: String? = null,
    val accountIconType: String? = null,
    val accountType: String? = null,
    val afterNextStatementDate: AfterNextStatementDate? = null,
    val authorizationsAmount: AuthorizationsAmount? = null,
    val c2cOutLimit: C2cOutLimit? = null,
    val c2cOutLimitBorder: C2cOutLimitBorder? = null,
    val cardNumbers: List<CardNumber> = emptyList(),
    val clientUnverifiedFlag: String? = null,
    val creationDate: CreationDate? = null,
    val creditLimit: CreditLimit? = null,
    val currency: Currency? = null,
    val currentMinimalPayment: CurrentMinimalPayment? = null,
    val currentRecommendedPayment: CurrentRecommendedPayment? = null,
    val debtAmount: DebtAmount? = null,
    val debtAmountWithAuths: DebtAmountWithAuths? = null,
    val debtBalance: DebtBalance? = null,
    val defaultMonthlyCashLimit: DefaultMonthlyCashLimit? = null,
    val defaultMonthlyTinkoffCashInsertionLimit: DefaultMonthlyTinkoffCashInsertionLimit? = null,
    val defaultMonthlyTinkoffCashLimit: DefaultMonthlyTinkoffCashLimit? = null,
    val defaultRenewalAmountLeft: DefaultRenewalAmountLeft? = null,
    val dueDate: DueDate? = null,
    val emoneyFlag: Boolean? = null,
    val externalAccountNumber: String? = null,
    val feeAndFinesBalance: FeeAndFinesBalance? = null,
    val feeNextChargeDate: FeeNextChargeDate? = null,
    val feeNextChargeText: String? = null,
    val hidden: Boolean? = null,
    val id: String? = null,
    val identificationState: String? = null,
    val imported: Boolean? = null,
    val interest: Interest? = null,
    val isCrowdfunding: Boolean? = null,
    val lastPaymentDate: LastPaymentDate? = null,
    val lastStatementDate: LastStatementDate? = null,
    val lastStatementDebtAmount: LastStatementDebtAmount? = null,
    val linkedAccountNumber: String? = null,
    val loyalty: List<Loyalty>,
    val marketingName: String? = null,
    val moneyAmount: MoneyAmount? = null,
    val monthlyCashLimit: MonthlyCashLimit? = null,
    val monthlyTinkoffCashInsertionLimit: MonthlyTinkoffCashInsertionLimit? = null,
    val monthlyTinkoffCashLimit: MonthlyTinkoffCashLimit? = null,
    val multiCardCluster: MultiCardCluster? = null,
    val name: String? = null,
    val nextStatementDate: NextStatementDate? = null,
    val overdraftFee: OverdraftFee? = null,
    val overdraftStatus: String? = null,
    val partNumber: String? = null,
    val pastDueDebt: PastDueDebt? = null,
    val rate: Double? = null,
    val rateHint: RateHint? = null,
    val renewalAmountLeft: RenewalAmountLeft? = null,
    val restructuringAccount: Boolean? = null,
    val status: String? = null,
    val sumPurchases: Double? = null,
    val tariffFileHash: String? = null,
    val tariffInfo: TariffInfo? = null,
    val totalExpense: TotalExpense? = null,
    val totalIncome: TotalIncome
)